
version: 2

models:
  - name: participant
    description: "Team participants"
    columns:
      - name: id
        description: "participant id"
      - name: name
      - name: position
      - name: abbreviation
    
  - name: group
    description: "Groups"
    columns:
      - name: id
      - name: name
      - name: parent_group_country_id
      - name: parent_group_country_name
      - name: parent_group_sports_id
      - name: parent_group_sports_name

  - name: outcome
    description: "outcome results"
    columns:
      - name: id
      - name: name
      - name: isTraded
      - name: formatDecimal
      - name: formatAmerican
      - name: status
      - name: trueOdds

  - name: specifier
    columns: 
      - name: key
      - name: value
      - name: type